# -*- coding: utf-8 -*-
"""Top Instagram Influencers Data (Cleaned).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xh2VsI2eXEaRh4YWVNBpCOYDVxVXqaHa

Data Loading and Pre Processing
"""

import pandas as pd
import numpy as np

df=pd.read_csv('/content/top_insta_influencers_data.csv')

print(df.info())
print(df.describe())

df.drop_duplicates(inplace=True)

for column in df.columns:
    if df[column].dtype == 'object':
        df[column].fillna(df[column].mode()[0], inplace=True)
    else:
        df[column].fillna(df[column].median(), inplace=True)

for col in ['followers', 'posts', 'total_likes']:
    df[col] = (df[col].astype(str)
               .str.lower()
               .str.replace(',', '', regex=True)
               .str.replace('k', 'e3', regex=True)
               .str.replace('m', 'e6', regex=True)
               .str.replace('b', 'e9', regex=True))
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)

print(df[['influence_score','followers','avg_likes','60_day_eng_rate','new_post_avg_like']].describe())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,6))
sns.scatterplot(data=df,x='followers',y='60_day_eng_rate',hue='country',alpha=0.7)
plt.title('Followers vs 60-Day engagement Rate')
plt.xlabel('Number of followers')
plt.ylabel('60-day Engagement rate(%)')
plt.legend(title='Country')
plt.show()

"""Distribution of Score"""

plt.figure(figsize=(10,5))
sns.histplot(df['influence_score'],bins=20,kde=True)
plt.title('Distribution of Influence score')
plt.xlabel('Influence Score')
plt.show()

"""Most Active Countries"""

top_countries=df['country'].value_counts().head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=top_countries.index,y=top_countries.values,palette="viridis")
plt.title('Top 10 countries by Number of Influencers')
plt.xlabel('Country')
plt.ylabel('Number of Influencers')
plt.show()

df['avg_likes'] = (df['avg_likes'].astype(str)
               .str.lower()
               .str.replace(',', '', regex=True)
               .str.replace('k', 'e3', regex=True)
               .str.replace('m', 'e6', regex=True)
               .str.replace('b', 'e9', regex=True))
df['avg_likes'] = pd.to_numeric(df['avg_likes'], errors='coerce').fillna(0)

df['like_follower_ratio'] = df['total_likes'] / df['followers']
df['post_follower_ratio'] = df['posts'] / df['followers']
df['avg_likes_ratio'] = df['avg_likes'] / df['followers']

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

for col in ['60_day_eng_rate']:
    df[col] = (df[col].astype(str)
               .str.replace('%', '', regex=True))
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

for col in ['new_post_avg_like']:
    df[col] = (df[col].astype(str)
               .str.lower()
               .str.replace(',', '', regex=True)
               .str.replace('k', 'e3', regex=True)
               .str.replace('m', 'e6', regex=True)
               .str.replace('b', 'e9', regex=True))
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

X=df[['followers','avg_likes','60_day_eng_rate','new_post_avg_like','like_follower_ratio','post_follower_ratio']]
y=df['influence_score']

X_train, X_test, y_train, y_test = train_test_split(X, y,
 test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestRegressor(n_estimators=100,
 random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean squared Error: {mse}')
print(f'R^2 Score: {r2}')

feature_importances = pd.Series(model.feature_importances_,index=X.columns)
feature_importances.sort_values().plot(kind='barh',title='Feature Importance')
plt.show()

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, alpha=0.6)
plt.plot([y.min(), y.max()], [y.min(), y.max()], '--',
color='red')
plt.xlabel('True Influence Score')
plt.ylabel('Predicted Influence Score')
plt.title('True vs Predicted Influence Score')
plt.show()

y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean squared Error: {mse}')
print(f'R^2 Score: {r2}')

dictionary={'Names':["Alice","Oggy","Modi","SRK","TOnyStark"],"Marks":[10,12,15,18,20]}
df=pd.DataFrame(dictionary)
df.head()

print(df['Names'])

print(df.loc[3])

insta_df=pd.read_csv('/content/top_insta_influencers_data.csv')
print('Dataset is Ready to use')

insta_df.head(25)

insta_df.info()

insta_df.shape

import matplotlib.pyplot as plt
import seaborn as sns

country=insta_df['country'].value_counts()

country

plt.figure(figsize=(15,8))
plt.title('Influencers on Instagram From nations')
sns.countplot(x=insta_df["country"])
plt.xticks(rotation=90)

insta_df.duplicated().sum()

insta_df.describe()

insta_df[['channel_info','followers','60_day_eng_rate']]

replace={'b': 'e9','m': 'e6','k': 'e3', '%': ''}
convert_column=['total_likes','posts','followers','avg_likes','60_day_eng_rate','new_post_avg_like']
insta_df[convert_column]=insta_df[convert_column].replace(replace,regex=True).astype(float)
insta_df[convert_column]

high_follower_df=insta_df[insta_df['followers']>1_000_000]
high_follower_df

high_engagement_df=insta_df[insta_df['60_day_eng_rate']>5]
high_engagement_df

top10_er = insta_df.drop(["rank","influence_score","avg_likes","new_post_avg_like","total_likes","country"],axis=1)
top10_er.head(10)

replace={'b': 'e9','m':'e6','k': 'e3','%': ''}
converted_data=top10_er['60_day_eng_rate'].replace(replace,regex=True).astype(float)
converted_data.head()

insta_df.isnull().sum

insta_df['60_day_eng_rate'].fillna(insta_df['60_day_eng_rate'].mean(),inplace=True)

insta_df.dropna(inplace=True)
print("Data Cleaned")

country=insta_df['country'].value_counts()[:20].to_list()
name_countries=insta_df['country'].value_counts().index[:20].to_list()
name_countries.append("Others")
max20=sum(country)
others=len(insta_df)-max20
country.append(others)

plt.figure(figsize=(10,8))
sns.barplot(x=country,y=name_countries,palette='viridis')
plt.title('Distribution of Influencersby country')
plt.xlabel('Number of Influencers')
plt.ylabel('Country')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

features=insta_df[['followers','influence_score','country']]
target=insta_df['60_day_eng_rate']

encoder=LabelEncoder()
features['country_encoded']=encoder.fit_transform(features['country'])
print("Encoding Completed")

features=features[['followers','influence_score','country_encoded']]

features

X_train, X_test,y_train,y_test=train_test_split(features,
target,test_size=0.1,random_state=42)

lr_model=LinearRegression()
lr_model.fit(X_train,y_train)
print("Training Completed")

rf_model = RandomForestRegressor(n_estimators=100,
                                 random_state=42)
rf_model.fit(X_train, y_train)
print("Training Completed")

lr_preds=lr_model.predict(X_test)
rf_preds=rf_model.predict(X_test)

lr_preds

lr_mse=mean_squared_error(y_test,lr_preds)
rf_mse=mean_squared_error(y_test,rf_preds)

print("Linear Regression MSE:",lr_mse)
print("Random Forest MSE:",rf_mse)

plt.figure(figsize=(10,5))
sns.scatterplot(x=y_test,y=lr_preds,color='blue')
plt.plot([y_test.min(),y_test.max()],[y_test.min(),y_test.max()],'r--')
plt.xlabel("Actual Engagement Rate")
plt.ylabel("Predicted Engagement Rate")
plt.title("Actual vs Predicted Engagement Rate")
plt.show()

fig,axes=plt.subplots(1,3,figsize=(18,5))
sns.scatterplot(ax=axes[0], x=X_test['followers'], y=y_test, label="Actual", color='blue')
sns.lineplot(ax=axes[0], x=X_test['followers'], y=lr_model.predict(X_test), label="Predicted", color='Red')
axes[0].set_title("Followers vs Engagement Rate")
axes[0].set_xlabel("Followers")
axes[0].set_ylabel("Engagement Rate")
sns.scatterplot(ax=axes[1], x=X_test['influence_score'],
y=y_test, label="Actual", color='blue')
sns.lineplot(ax=axes[1], x=X_test['influence_score'],
y=lr_model.predict(X_test), label="Predicted", color='red')
axes[1].set_title("Influence Score vs Engagement Rate")
axes[1].set_xlabel("Influence Score")
axes[1].set_ylabel("Engagement Rate")
sns.scatterplot(ax=axes[2], x=X_test['country_encoded'],
y=y_test, label="Actual", color='blue')
sns.lineplot(ax=axes[2], x=X_test['country_encoded'],
y=lr_model.predict(X_test), label="Predicted", color='red')
axes[2].set_title("Country Encoded vs Engagement Rate")
axes[2].set_xlabel("Country Encoded")
axes[2].set_ylabel("Engagement Rate")
plt.tight_layout()
plt.show()

predictions_df=X_test.copy()
predictions_df['Actual Engagement Rate']=y_test.values
predictions_df['Predicted Engagement Rate']=lr_preds

predictions_df.head()

insta_df.head()

bins=[0,1,3,insta_df['60_day_eng_rate'].max()]
labels=['Low','Medium','High']
insta_df['engagement_rate_class']=pd.cut(insta_df['60_day_eng_rate'],bins=bins,labels=labels)
insta_df.head(20)

high_engagement_df=insta_df[insta_df['engagement_rate_class']=='High']
high_engagement_df

encoder=LabelEncoder()
insta_df['country_encoded']=encoder.fit_transform(insta_df['country'])

features = insta_df[['followers', 'influence_score',
'country_encoded']]
target = insta_df['engagement_rate_class']

X_train,X_test,y_train,y_test=train_test_split(features,target,test_size=0.2,random_state=42)
print("TTS Completed")

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,accuracy_score

classifier=RandomForestClassifier(n_estimators=100,random_state=42)
classifier.fit(X_train,y_train)
print("Model trained")

y_pred=classifier.predict(X_test)
y_pred

accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:"+str(float(accuracy)*100)+"%")
print("\nClassification Report:\n",classification_report(y_test,y_pred))

from sklearn.metrics import confusion_matrix

conf_matrix=confusion_matrix(y_test,y_pred,labels=labels)

plt.figure(figsize=(8,6))
sns.heatmap(conf_matrix,annot=True,fmt='d',cmap='Blues',xticklabels=labels,yticklabels=labels)
plt.xlabel('Predicted Class')
plt.ylabel('Actual Class')
plt.title('Confusion Matrix of Engagement Rate classification')
plt.show()

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
sns.countplot(x=y_test,order=labels,palette="viridis")
plt.title("Actual class distribution")
plt.xlabel("Engagement Rate class")
plt.ylabel("count")
plt.subplot(1,2,2)
sns.countplot(x=y_pred,order=labels,palette="viridis")
plt.title("Predicted class distribution")
plt.xlabel("Engagement Rate class")
plt.ylabel("count")
plt.tight_layout()
plt.show()